FROM ubuntu:jammy-20220531 AS build

RUN apt update && \
    apt install wget -y && \
    apt install build-essential -y && \
    apt install curl -y && \
    apt install ca-certificates -y && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-ca-certificates

RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
RUN dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

COPY . /bright_dispute/

RUN rustup install 1.69
RUN rustup default 1.69
RUN rustup component add rust-src --toolchain 1.69
RUN rustup target add wasm32-unknown-unknown --toolchain 1.69
RUN cargo install --force --locked cargo-contract --version 3.0.1

WORKDIR /bright_dispute/contract
RUN cargo test --release
