name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.69
            override: true
      - name: Updating submodules
        run: git submodule update --init --recursive
      - name: Update Rust environment
        run: rustup component add rust-src --toolchain 1.69-x86_64-unknown-linux-gnu
      - name: Adding WebAssembly target
        run: rustup target add x86_64-unknown-linux-gnu wasm32-unknown-unknown
      - name: Build bright disputes
        run: cd contract && cargo build --release --verbose
      - name: Run bright disputes unit tests
        run: cd contract && cargo test --release --verbose
